# Generated by Django 5.2.5 on 2025-09-02 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0003_stockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategyBacktest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_return', models.FloatField(default=0.0)),
                ('max_drawdown', models.FloatField(default=0.0)),
                ('sharpe_ratio', models.FloatField(blank=True, null=True)),
                ('buy_signals_count', models.IntegerField(default=0)),
                ('sell_signals_count', models.IntegerField(default=0)),
                ('market_return', models.FloatField(default=0.0)),
                ('strategy_return', models.FloatField(default=0.0)),
                ('results_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_data.tradingstrategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], max_length=4)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence', models.FloatField(default=1.0)),
                ('indicators', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_data.tradingstrategy')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='stock_data__symbol_93300e_idx'), models.Index(fields=['signal_type', 'timestamp'], name='stock_data__signal__c274a0_idx')],
            },
        ),
    ]
